[tool.poetry]
name = "server-python"
version = "0.1.0"
description = ""
authors = ["Pacharapol Withayasakpunt <patarapolw@gmail.com>"]
license = "ISC"

[tool.poetry.dependencies]
python = "^3.6"
gtts = "^2.1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
